apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels: 
    purpose: ebs-static
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c #Pods will be created in the mentioned AZ.
  containers:
  - name: nginx
    image: nginx