apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels: 
    purpose: toleration
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  -  key: "hardware"
     operator: "Equal"
     value: "gpu"
     effect: "NoSchedule"
  -  key: "hardware"
     operator: "Equal"
     value: "gpu"
     effect: "NoExecute"